server:
  port: 8763


#配置注册中心的位置，并把自己注册进去
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8769/eureka/

#当前项目名字
spring:
  application:
    name: service-psid

